In [ ]:
//Numpy

In [2]:
data=[18,3,29,12,90,78]
print(type(data))

<class 'list'>


In [3]:
import numpy as np
arr_data=np.array(data)
arr_data

array([18,  3, 29, 12, 90, 78])

In [9]:
max_data=np.max(arr_data)
print(max_data)

90


In [8]:
mean_data=np.mean(arr_data)
print(mean_data)

38.333333333333336


In [11]:
min_data=np.min(arr_data)
print(min_data)

3


In [12]:
zero_func=np.zeros([3,5])
zero_func

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
ones_func=np.ones([6,9])
ones_func

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
random_num=np.random.rand(5,5)
random_num

array([[0.18426072, 0.51531721, 0.32605223, 0.41021788, 0.15730213],
       [0.83481318, 0.89859646, 0.97729268, 0.34422763, 0.45000989],
       [0.66021318, 0.15796908, 0.2077231 , 0.98073834, 0.78780289],
       [0.29580806, 0.12849955, 0.24841178, 0.11003935, 0.64714761],
       [0.91930458, 0.8829104 , 0.06156864, 0.53501055, 0.04686081]])

In [19]:
reshape_func=[2,5,8,0,4,6,8,12,5,6,8,6,2,7,8,9,8,5]
data=np.reshape(reshape_func,(2,9))
data

array([[ 2,  5,  8,  0,  4,  6,  8, 12,  5],
       [ 6,  8,  6,  2,  7,  8,  9,  8,  5]])

In [25]:
arrange=np.arange(18).reshape(2,9)
arrange

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [28]:
arr = np.array([23,29,21,300,403,409,500,503,300,23])
d=np.unique(arr)
d

array([ 21,  23,  29, 300, 403, 409, 500, 503])

In [29]:
arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


In [30]:
arr_1 = np.array([13,28,32])
arr_2 = np.array([14,56,76])
print(np.concatenate((arr_1,arr_2)))

[13 28 32 14 56 76]


In [34]:
shape_func=np.shape(ones_func)
shape_func

(6, 9)

In [35]:
salary=np.array([30000,40000,50000,60000,700000])
salary

array([ 30000,  40000,  50000,  60000, 700000])

In [36]:
salary[salary>=56000]

array([ 60000, 700000])

In [37]:
salary[salary<=56000]

array([30000, 40000, 50000])

In [38]:
salary+10000

array([ 40000,  50000,  60000,  70000, 710000])

In [39]:
arr_datas=np.arange(50).reshape(5,10)
arr_datas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_datas[1:3,:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [43]:
arr_datas[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [44]:
arr_datas[:,::3]

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19],
       [20, 23, 26, 29],
       [30, 33, 36, 39],
       [40, 43, 46, 49]])

In [45]:
arr_datas[0:1,1:3]

array([[1, 2]])